apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: server
spec:
  service:
    name: server
  calls:
    - name: arn:aws:s3:::otterize-tutorial-bucket-*/*
      type: aws
      awsActions:
        - "s3:PutObject"
    - name: arn:aws:iam::353146681200:role/otr-otterize-tutorial-iam.server@orisho-otterize-iam-eks--ee4773
      type: aws
      awsActions:
        - sts:AssumeRoleWithWebIdentity
    - name: arn:aws:s3:::otterize-tutorial-bucket-1711273272
      type: aws
      awsActions:
        - s3:ListBucket
    - name: arn:aws:s3:::otterize-tutorial-bucket-1711273272/*
      type: aws
      awsActions:
        - s3:PutObject
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObjectTagging
        - s3:PutObjectAcl
    - name: arn:aws:s3:::otterize-tutorial-bucket-blabla
      type: aws
      awsActions:
        - s3:ListBucket
    - name: arn:aws:s3:::otterize-tutorial-bucket-blabla/*
      type: aws
      awsActions:
        - s3:PutObject
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObject
        - s3:PutObjectTagging
        - s3:PutObjectAcl
    - name: arn:aws:s3:::otterize-tutorial-bucket-testing
      type: aws
      awsActions:
        - s3:ListBucket
    - name: arn:aws:s3:::otterize-tutorial-bucket-testing/*
      type: aws
      awsActions:
        - s3:PutObject
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObject
        - s3:PutObjectTagging
        - s3:PutObjectAcl
    - name: otterize-iamlive.otterize-system
    - name: arn:aws:s3:::otterize-tutorial-bucket-blabla/*
      type: aws
      awsActions:
        - s3:PutObject
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObject
        - s3:PutObjectTagging
        - s3:PutObjectAcl
        - s3:PutObject
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObjectTagging
        - s3:PutObjectAcl
    - name: arn:aws:s3:::otterize-tutorial-bucket-blabla/*
      type: aws
      awsActions:
        - s3:PutObject
        - s3:PutObject
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObject
        - s3:PutObjectTagging
        - s3:PutObjectAcl
        - s3:PutObject
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObjectTagging
        - s3:PutObjectAcl
    - name: arn:aws:s3:::otterize-tutorial-bucket-blabla/*
      type: aws
      awsActions:
        - s3:PutObject
        - s3:PutObject
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObject
        - s3:PutObjectTagging
        - s3:PutObjectAcl
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObject
        - s3:PutObjectTagging
        - s3:PutObjectAcl
        - s3:PutObject
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObjectTagging
        - s3:PutObjectAcl
    - name: arn:aws:s3:::otterize-tutorial-bucket-blabla/*
      type: aws
      awsActions:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:PutObject
        - s3:PutObject
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObject
        - s3:PutObjectTagging
        - s3:PutObjectAcl
        - s3:PutObject
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObjectTagging
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObject
        - s3:PutObjectTagging
        - s3:PutObjectAcl
        - s3:PutObject
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObjectTagging
        - s3:PutObjectAcl